spring:
  datasource:
    url: jdbc:h2:file:./data/todos
    driver-class-name: org.h2.Driver
    username: h2
    password: ""
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

server:
  port: 8000
